### ISSUE TITLE
Add an option so that the autogenerated cardinal values can be changed

### ISSUE THREAD

**Issue by torifat** [messageformat/gettext-to-messageformat#1]
Hi

First of all, thanks for your awesome work on all i18n related stuff 👍

```
pluralFunc.cardinal = new Array(nplurals).fill().map((_, i) => 'p' + i)
```
Currently this thing generates a cardinal array like `[p0, p1]`. It would be better if we could change it to `[one, other]`. Currently I can pass a `pluralFunction` but for that first, I need to know the `language`.
I was hopping if we could pass an option like following.
```
cardinalFunction: (language) => [];
```

If you agree with the proposal then I can send a PR for the change.

Cheers.

**Comment by eemeli** [comment]
The difficulty with automatically getting CLDR categories out of Gettext functions is that their order varies between implementations; this is true in particular for the `zero` category.

Have I understood right that the idea would be to support pluralisation in .po files that include a `Language` header but not a `Plural-Forms` header, and to wrap that language's default pluralisation function (provided by Messageformat) by including an option for `parsePo()` with the appropriate categories of `msgstr[0]`, `msgstr[1]`, etc. as used in the input file?

**Comment by torifat** [comment]
Actually, it can have both `Language` and `Plural-Forms`. Currently `parsePo()` create class names as `p0`, `p1`, `p2`, etc. I'm just looking for an option to use `zero`, `one`, `few`, `other` etc. instead of those.

**Comment by eemeli** [comment]
So what would be the use case here? Are you intending to use gettext data with some other tool than `messageformat`, or what? Might it be enough for you to just wrap the provided function with your own, which would encode your index -> category mapping? Something like this:

```js
const { parsePo } = require('gettext-to-messageformat')
let { pluralFunction } = parsePo(...)
pluralFunction = (n) => {
  switch (pluralFunction(n)) {
    case 'p0': return 'one'
    case 'p1': return 'zero'
    default: return 'other'
  }
}
pluralFunction.cardinal = ['one', 'zero', 'other']
```

I ask about the use case, because I'm not sure how often this would be actually useful. If it's really rare, it would probably make sense for you to just implement it in your own app, but if it could be more common then including a wrapper option would make good sense.

**Comment by torifat** [comment]
Yes, I will use `cldr` package to get the appropriate list for any particular language. The use case it that I'm trying to use the `translations` and currenlty they have `p0`, `p1` after parsing.

I can write a wrapper function but the problem is that the `translations` are already parsed and they have `p0`, `p1`, etc. inside of them. Currently, I'm traversing them and replacing them like the function you wrote but I was thinking it would be nice if I could pass an array beforehand.

Another way I could achive it is by passing a custom `pluralFunction` but again I need to know the language to construct a proper `pluralFunction`.

**Comment by eemeli** [comment]
Sorry for having left this sitting here. I think what you're describing sounds like it has merit, but that the proposed API for it is still a bit fuzzy for me. So to answer your original question, yes, a PR on this would be good.

**Comment by eemeli** [comment]
Closing as stale.
